// front/styles/styles.js
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

// *** GLOBAL FONT AYARI - Tüm fontları buradan değiştirebilirsiniz ***
const GLOBAL_FONT_FAMILY = '"Kalam", "Comic Sans MS", cursive, sans-serif';

// Responsive font boyutları için yardımcı fonksiyon
const calcFontSize = (size) => {
  return `clamp(${size * 0.8}px, ${size * 0.15}vw, ${size * 1.2}px)`;
};

// Responsive boyutlar için yardımcı fonksiyon
const calcSize = (size) => {
  return `clamp(${size * 0.8}px, ${size * 0.1}vw, ${size * 1.2}px)`;
};

// Ortak yazı stilleri
const textStyles = {
  primary: {
    fontFamily: GLOBAL_FONT_FAMILY,
    color: '#fff',
    letterSpacing: calcSize(1),
    textShadow: `0 ${calcSize(2)} ${calcSize(4)} rgba(0,0,0,0.2)`,
  }
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(26, 31, 37, 0.25)',
    height: '100vh',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflowY: 'hidden',
    zIndex: 1,
    '&::-webkit-scrollbar': {
      display: 'none',
    },
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
    '&::-webkit-scrollbar-thumb': {
      display: 'none',
    },
  },
  scrollViewContent: {
    flex: 1,
    backgroundColor: 'rgba(26, 31, 37, 0.5)',
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    margin: 0,
    overflowY: 'auto',
  },
  },
  heroTitle: {
    ...textStyles.primary,
    fontSize: 'clamp(16px, 3vw, 42px)',
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 'clamp(0.5vh, 1vw, 1vh)',
    marginTop: 'clamp(1vh, 2vw, 2vh)',
    textShadow: `0 clamp(2px, 0.4vw, 4px) clamp(6px, 1.2vw, 12px) rgba(0,123,255,0.3), 0 clamp(1px, 0.2vw, 2px) clamp(3px, 0.6vw, 6px) rgba(0,0,0,0.6), 0 0 clamp(10px, 2vw, 20px) rgba(0,123,255,0.15)`,
    // animation removed - React Native Web doesn't support CSS animations
    lineHeight: 'clamp(20px, 3.5vw, 48px)',
    letterSpacing: 'clamp(0.1px, 0.02vw, 0.3px)',
  },
  heroSubtitle: {
    ...textStyles.primary,
    fontSize: 'clamp(10px, 1.8vw, 18px)',
    textAlign: 'center',
    opacity: 0.9,
    marginBottom: 'clamp(1vh, 2vw, 2vh)',
    textShadow: `0 clamp(2px, 0.4vw, 4px) clamp(6px, 1.2vw, 12px) rgba(0,123,255,0.3), 0 clamp(1px, 0.2vw, 2px) clamp(3px, 0.6vw, 6px) rgba(0,0,0,0.6), 0 0 clamp(10px, 2vw, 20px) rgba(0,123,255,0.15)`,
    lineHeight: 'clamp(14px, 2.2vw, 22px)',
    paddingHorizontal: 'clamp(10px, 2vw, 20px)',
  },
  mainButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 'clamp(8px, 2vw, 16px)',
    padding: 'clamp(8px, 1.5vw, 16px)',
    marginTop: 'clamp(20px, 4vw, 40px)',
    marginLeft: 'auto',
    marginRight: 'auto',
    transition: 'all 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    minHeight: 'clamp(80px, 15vw, 200px)',
    height: 'auto',
    maxHeight: 'clamp(30vh, 40vw, 40vh)',
    flexWrap: 'wrap',
    width: '100%',
    maxWidth: calcSize(1400),
    alignSelf: 'center'
  },
  mainButtonsContainerSmall: {
    minHeight: 'clamp(60px, 12vw, 80px)',
    height: 'auto',
    marginTop: 'clamp(0.5vh, 1vw, 1vh)',
    marginBottom: 'clamp(0.5vh, 1vw, 1vh)',
    marginLeft: 'auto',
    marginRight: 'auto',
    gap: 'clamp(4px, 1vw, 8px)',
    padding: 'clamp(4px, 0.8vw, 8px)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'nowrap',
    width: '100%',
    maxWidth: calcSize(1400),
    alignSelf: 'center'
  },
  mainButton: {
    width: 'clamp(40%, 45vw, 45%)',
    maxWidth: calcSize(400),
    minHeight: 'clamp(60px, 12vw, 150px)',
    height: 'auto',
    maxHeight: 'clamp(25vh, 35vw, 35vh)',
    backgroundColor: '#007bff',
    backgroundColor: '#007bff',
    borderRadius: 'clamp(12px, 2.5vw, 25px)',
    justifyContent: 'center',
    alignItems: 'center',
    transition: 'all 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    cursor: 'pointer',
    overflow: 'hidden',
    boxShadow: `0 clamp(10px, 2vw, 20px) clamp(20px, 4vw, 40px) rgba(0,123,255,0.3), 
                0 clamp(5px, 1vw, 10px) clamp(10px, 2vw, 20px) rgba(0,123,255,0.2), 
                inset 0 clamp(2px, 0.4vw, 4px) clamp(6px, 1.2vw, 12px) rgba(0,56,179,0.3), 
                inset 0 clamp(-2px, -0.4vw, -4px) clamp(6px, 1.2vw, 12px) rgba(77,163,255,0.2)`,
    border: 'clamp(2px, 0.3vw, 3px) solid #007bff',
    padding: 'clamp(8px, 1.5vw, 20px)',
    position: 'relative',
    overflow: 'hidden',
    '@media (maxWidth: 768)': {
      width: 'clamp(40%, 45vw, 45%)',
      minHeight: 'clamp(35px, 7vw, 50px)',
      height: 'clamp(35px, 7vw, 50px)',
      maxHeight: 'clamp(35px, 7vw, 50px)',
      padding: 'clamp(6px, 1vw, 10px) clamp(12px, 2vw, 20px)',
      fontSize: 'clamp(10px, 1.5vw, 14px)',
    },
    '&:hover': {
      transform: 'translateY(-8px) scale(1.05)',
      boxShadow: `0 ${calcSize(25)} ${calcSize(50)} rgba(0,123,255,0.6), 0 ${calcSize(10)} ${calcSize(25)} rgba(0,123,255,0.4), 0 0 ${calcSize(40)} rgba(0,123,255,0.3), inset 0 ${calcSize(-2)} ${calcSize(8)} rgba(0,0,0,0.2), inset 0 ${calcSize(2)} ${calcSize(8)} rgba(255,255,255,0.2)`,
      backgroundColor: '#0056b3',
    },
    '&:active': {
      transform: 'translateY(-4px) scale(0.98)',
      boxShadow: `0 ${calcSize(8)} ${calcSize(20)} rgba(0,123,255,0.4), inset 0 ${calcSize(4)} ${calcSize(12)} rgba(0,0,0,0.3)`,
      backgroundColor: '#003d82',
    },
  },
  mainButtonSmall: {
    width: 'clamp(35%, 40vw, 40%)',
    maxWidth: calcSize(200),
    height: 'clamp(40px, 8vw, 50px)',
    minHeight: 'auto',
    boxShadow: `0 clamp(2px, 0.4vw, 4px) clamp(4px, 0.8vw, 8px) rgba(0,123,255,0.2)`,
    padding: 'clamp(6px, 1vw, 10px)',
    '@media (maxWidth: 768)': {
      width: 'clamp(40%, 45vw, 45%)',
    },
  },
  mainButtonText: {
    ...textStyles.primary,
    fontSize: 'clamp(12px, 2.2vw, 36px)',
    fontWeight: '600',
    transition: 'all 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    whiteSpace: 'nowrap',
    textAlign: 'center',
    color: '#fff',
    textShadow: `0 clamp(1px, 0.2vw, 2px) clamp(2px, 0.4vw, 4px) rgba(0,0,0,0.5)`,
    letterSpacing: 'clamp(0.1px, 0.05vw, 0.5px)',
    lineHeight: 'clamp(16px, 2.6vw, 44px)',
    '@media (maxWidth: 768)': {
      fontSize: 'clamp(10px, 1.5vw, 18px)',
      lineHeight: 'clamp(14px, 2vw, 22px)',
    },
  },
  mainButtonTextSmall: {
    fontSize: 'clamp(10px, 1.2vw, 16px)',
    textShadow: 'none',
    lineHeight: 'clamp(14px, 1.8vw, 20px)',
  },
  glassCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 'clamp(12px, 2.5vw, 25px)',
    borderWidth: 'clamp(1px, 0.2vw, 2px)',
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderStyle: 'solid',
    paddingTop: 'clamp(8px, 2.4vw, 24px)',
    paddingLeft: 'clamp(12px, 3vw, 60px)',
    paddingRight: 'clamp(12px, 3vw, 60px)',
    paddingBottom: 'clamp(20px, 4vw, 40px)',
    marginVertical: 'clamp(6px, 1.2vw, 12px)',
    boxShadow: `0 clamp(8px, 1.5vw, 15px) clamp(22px, 4.5vw, 45px) rgba(0,0,0,0.25), 0 clamp(2px, 0.5vw, 5px) clamp(10px, 2vw, 20px) rgba(0,123,255,0.06), inset 0 clamp(0.5px, 0.1vw, 1px) clamp(1px, 0.2vw, 2px) rgba(255,255,255,0.15)`,
    backdropFilter: 'blur(16px) saturate(180%)',
    width: '95%',
    maxWidth: 'clamp(500px, 60vw, 900px)',
    alignSelf: 'center',
    overflow: 'visible',
    boxSizing: 'border-box',
    transition: 'all 0.3s ease',
    marginLeft: 'auto',
    marginRight: 'auto',
    '&:hover': {
      boxShadow: `0 ${calcSize(20)} ${calcSize(55)} rgba(0,0,0,0.3), 0 ${calcSize(8)} ${calcSize(25)} rgba(0,123,255,0.08), inset 0 ${calcSize(1)} ${calcSize(2)} rgba(255,255,255,0.2)`,
      borderColor: 'rgba(255, 255, 255, 0.3)',
    },
  },
  cardTitle: {
    ...textStyles.primary,
    fontSize: 'clamp(12px, 2vw, 24px)',
    fontWeight: '700',
    marginBottom: 'clamp(6px, 1.6vw, 16px)',
    textAlign: 'center',
    textShadow: `0 clamp(1.5px, 0.3vw, 3px) clamp(4px, 0.8vw, 8px) rgba(0,123,255,0.2), 0 clamp(0.5px, 0.1vw, 1px) clamp(1.5px, 0.3vw, 3px) rgba(0,0,0,0.5)`,
    lineHeight: 'clamp(16px, 2.5vw, 30px)',
    padding: 'clamp(2px, 0.5vw, 4px)',
  },
  flexRowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 'clamp(4px, 0.8vw, 8px)',
    padding: 'clamp(2px, 0.8vw, 8px)',
    width: '100%',
    maxWidth: '100%',
    boxSizing: 'border-box',
  },
  subButton: {
    backgroundColor: '#6c757d',
    backgroundColor: '#6c757d',
    padding: 'clamp(6px, 1.2vw, 12px)',
    borderRadius: 'clamp(10px, 2.5vw, 25px)',
    flex: 1,
    minWidth: 'clamp(100px, 18vw, 180px)',
    maxWidth: 'clamp(180px, 30vw, 300px)',
    height: 'clamp(50px, 10vw, 100px)',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    transition: 'all 0.35s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    overflow: 'hidden',
    boxShadow: `0 clamp(6px, 1.2vw, 12px) clamp(12px, 2.5vw, 25px) rgba(0,0,0,0.3), 
                0 clamp(2px, 0.5vw, 5px) clamp(6px, 1.2vw, 12px) rgba(0,0,0,0.2), 
                inset 0 clamp(1.5px, 0.3vw, 3px) clamp(5px, 1vw, 10px) rgba(52,58,64,0.35), 
                inset 0 clamp(-1.5px, -0.3vw, -3px) clamp(5px, 1vw, 10px) rgba(138,145,153,0.25)`,
    border: 'clamp(1px, 0.3vw, 3px) solid #6c757d',
    margin: 'clamp(2px, 0.8vw, 8px)',
    position: 'relative',
    '@media (maxWidth: 768)': {
      height: 'clamp(40px, 8vw, 80px)',
      padding: 'clamp(4px, 0.8vw, 8px)',
      minWidth: 'clamp(90px, 15vw, 150px)',
    },
    '&:hover': {
      transform: 'translateY(-5px) scale(1.03)',
      boxShadow: `0 ${calcSize(15)} ${calcSize(35)} rgba(108,117,125,0.5), 0 ${calcSize(5)} ${calcSize(15)} rgba(0,0,0,0.3), 0 0 ${calcSize(25)} rgba(108,117,125,0.3), inset 0 ${calcSize(-1)} ${calcSize(5)} rgba(0,0,0,0.2), inset 0 ${calcSize(1)} ${calcSize(5)} rgba(255,255,255,0.2)`,
      backgroundColor: 'rgba(52, 58, 64, 1)',
    },
    '&:active': {
      transform: 'translateY(-2px) scale(0.98)',
      boxShadow: `0 ${calcSize(5)} ${calcSize(15)} rgba(0,0,0,0.3), inset 0 ${calcSize(3)} ${calcSize(8)} rgba(0,0,0,0.3)`,
      backgroundColor: 'rgba(33, 37, 41, 1)',
    },
  },
  subButtonText: {
    ...textStyles.primary,
    fontSize: 'clamp(12px, 2vw, 24px)',
    fontWeight: '500',
    whiteSpace: 'nowrap',
    textAlign: 'center',
    lineHeight: 'clamp(16px, 2.4vw, 28px)',
    '@media (maxWidth: 768)': {
      fontSize: 'clamp(10px, 1.5vw, 18px)',
      lineHeight: 'clamp(14px, 2vw, 22px)',
    },
  },
  formContainer: {
    paddingTop: 'clamp(4px, 1.6vw, 16px)',
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: 'clamp(20px, 4vw, 40px)',
    width: '100%',
    maxWidth: '100%',
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 'clamp(8px, 2vw, 16px)',
    boxSizing: 'border-box',
    overflow: 'visible',
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: '100%',
    flexWrap: 'wrap',
    gap: 'clamp(4px, 1vw, 12px)',
    boxSizing: 'border-box',
    '@media (maxWidth: 600)': {
      flexDirection: 'column',
      gap: 'clamp(2px, 0.5vw, 4px)',
    },
  },
  formColumn: {
    flex: 1,
    minWidth: 'clamp(180px, 40vw, 250px)',
    maxWidth: '100%',
    padding: 'clamp(2px, 0.8vw, 8px)',
    boxSizing: 'border-box',
    '@media (maxWidth: 600)': {
      flex: 'none',
      minWidth: '100%',
      width: '100%',
      padding: '2px',
    },
  },
  formGroup: {
    marginBottom: 'clamp(4px, 1vw, 1vh)',
    width: '100%',
    maxWidth: '100%',
    boxSizing: 'border-box',
  },
  // Floating label container
  formFloatingContainer: {
    position: 'relative',
    width: '100%',
    marginBottom: 'clamp(10px, 1.5vw, 15px)',
  },
  
  // Label başlangıç stili (input içinde)
  formLabel: {
    ...textStyles.primary,
    position: 'absolute',
    left: 'clamp(12px, 2vw, 20px)',
    top: '50%',
    transform: 'translateY(-50%)',
    fontSize: 'clamp(10px, 1.4vw, 14px)',
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.5)',
    pointerEvents: 'none',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    zIndex: 1,
    backgroundColor: 'transparent',
    paddingLeft: 0,
    paddingRight: 0,
  },
  
  // Label floating durumu (yukarı çıkmış)
  formLabelFloating: {
    ...textStyles.primary,
    position: 'absolute',
    left: 'clamp(10px, 1.8vw, 18px)',
    top: 'clamp(-14px, -1.8vw, -18px)',
    transform: 'translateY(0)',
    fontSize: 'clamp(8px, 1.1vw, 11px)',
    fontWeight: '500',
    color: 'rgba(0, 123, 255, 0.9)',
    pointerEvents: 'none',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    zIndex: 2,
    backgroundColor: 'rgba(20, 25, 35, 0.95)',
    paddingLeft: 'clamp(4px, 0.8vw, 8px)',
    paddingRight: 'clamp(4px, 0.8vw, 8px)',
    paddingTop: 'clamp(1px, 0.2vw, 2px)',
    paddingBottom: 'clamp(1px, 0.2vw, 2px)',
    borderRadius: 'clamp(3px, 0.6vw, 6px)',
  },
  formInput: {
    backgroundColor: 'rgba(30, 35, 45, 0.9)',
    color: '#fff',
    borderRadius: 'clamp(6px, 1.2vw, 12px)',
    padding: 'clamp(6px, 1.2vw, 12px)',
    height: 'clamp(32px, 4.5vw, 45px)',
    fontSize: 'clamp(10px, 1.4vw, 14px)',
    letterSpacing: 'clamp(0.2px, 0.05vw, 0.5px)',
    fontFamily: GLOBAL_FONT_FAMILY,
    width: '100%',
    maxWidth: '100%',
    border: 'clamp(1px, 0.2vw, 2px) solid rgba(0,123,255,0.2)',
    boxShadow: `inset 0 clamp(1px, 0.2vw, 2px) clamp(2px, 0.4vw, 4px) rgba(0,0,0,0.1), 0 clamp(1px, 0.2vw, 2px) clamp(4px, 0.8vw, 8px) rgba(0,123,255,0.1)`,
    transition: 'all 0.3s ease',
    boxSizing: 'border-box',
    '&:focus': {
      outline: 'none',
      borderColor: 'rgba(0,123,255,0.5)',
      boxShadow: `0 0 0 clamp(1.5px, 0.3vw, 3px) rgba(0,123,255,0.2), inset 0 clamp(1px, 0.2vw, 2px) clamp(2px, 0.4vw, 4px) rgba(0,0,0,0.1), 0 clamp(2px, 0.4vw, 4px) clamp(6px, 1.2vw, 12px) rgba(0,123,255,0.2)`,
      transform: 'translateY(-1px)',
    },
  },
  formScrollContent: {
    paddingBottom: 'clamp(10px, 2vw, 20px)',
    width: '100%',
    maxWidth: '100%',
    boxSizing: 'border-box',
    overflow: 'hidden',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 'clamp(3px, 0.5vw, 5px)',
    width: '100%',
    maxWidth: '100%',
    boxSizing: 'border-box',
  },
  checkboxButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 'clamp(4px, 1vw, 10px)',
    padding: 'clamp(4px, 1vw, 10px)',
    height: 'clamp(28px, 4vw, 40px)',
    width: '100%',
    maxWidth: '100%',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxSizing: 'border-box',
    boxShadow: `0 clamp(2px, 0.4vw, 4px) clamp(6px, 1.2vw, 12px) rgba(0,0,0,0.2), inset 0 clamp(0.5px, 0.1vw, 1px) clamp(1px, 0.2vw, 2px) rgba(255,255,255,0.1)`,
    border: 'clamp(1px, 0.2vw, 2px) solid rgba(255,255,255,0.15)',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: `0 clamp(3px, 0.6vw, 6px) clamp(8px, 1.6vw, 16px) rgba(0,123,255,0.3), inset 0 clamp(0.5px, 0.1vw, 1px) clamp(1px, 0.2vw, 2px) rgba(255,255,255,0.15)`,
      backgroundColor: 'rgba(0, 123, 255, 0.2)',
    },
    '&:active': {
      transform: 'translateY(0px)',
      boxShadow: `0 clamp(1px, 0.2vw, 2px) clamp(4px, 0.8vw, 8px) rgba(0,0,0,0.2), inset 0 clamp(1px, 0.2vw, 2px) clamp(2px, 0.4vw, 4px) rgba(0,0,0,0.2)`,
    },
  },
  checkboxText: {
    ...textStyles.primary,
    fontSize: 'clamp(10px, 1.4vw, 14px)',
    marginLeft: 'clamp(4px, 0.8vw, 8px)',
    opacity: 0.9,
    lineHeight: 'clamp(14px, 1.8vw, 18px)',
  },
  tableContainer: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#1A1F2580',
    marginBottom: '16px',
    position: 'relative',
    zIndex: 1,
    borderRadius: '16px',
    overflow: 'hidden',
    
    /* .scrollable CSS'inden eklenen özellikler */
    boxSizing: 'border-box',
    paddingTop: '20px',
    paddingBottom: '8px',
    paddingLeft: '20px',
    paddingRight: '20px',
  },
  tableWrapper: {
    width: '100%',
    overflowX: 'auto',
    overflowY: 'auto',
    position: 'relative',
    marginLeft: 0,
    marginRight: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: '12px',
    backgroundColor: '#1A1F2580',
    borderRadius: '15px',
    
    /* Scrollbar stilleri */
    '&::-webkit-scrollbar': {
      width: 8,
      height: 8,
    },
    '&::-webkit-scrollbar-track': {
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderRadius: 4,
      marginLeft: '15px',
      marginRight: '15px',
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: 'rgba(0, 123, 255, 0.4)',
      borderRadius: 4,
    },
    '&::-webkit-scrollbar-thumb:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.6)',
    },
    '&::-webkit-scrollbar-button': {
      display: 'none',
    },
  },
  mainContainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    padding: '8px',
    paddingBottom: '0px',
    position: 'relative',
    zIndex: 1,
    transition: 'transform 0.3s ease',
    '@media (maxWidth: 768)': {
      scrollSnapAlign: 'start',
      scrollSnapStop: 'always',
    },
  },
  headerContainer: {
    position: 'sticky',
    top: 0,
    zIndex: 10,
    backgroundColor: '#1a1f25',
    transition: 'transform 0.3s ease',
    transform: 'translateY(0)',
    '&.hidden': {
      transform: 'translateY(-100%)',
    },
  },
  tableHeader: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#1A1F2580',
    position: 'sticky',
    top: 0,
    zIndex: 2,
    width: '100%',
    minWidth: 'fit-content',
    overflow: 'visible',
    borderTopLeftRadius: '15px',
    borderTopRightRadius: '15px',
    boxShadow: `0 ${calcSize(6)} ${calcSize(20)} rgba(0,0,0,0.2), inset 0 ${calcSize(1)} ${calcSize(2)} rgba(255,255,255,0.05)`,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(255,255,255,0.1)',
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,255,255,0.1)',
    boxSizing: 'border-box',
    '& > div': {
      '&:hover': {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        boxShadow: `inset 0 0 ${calcSize(15)} rgba(255,255,255,0.08)`,
      },
      '&:active': {
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
      },
    },
  },
  headerCell: {
    flexShrink: 0,
    borderRightStyle: 'solid',
    borderRightWidth: '1px',
    borderRightColor: 'rgba(255, 255, 255, 0.2)',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '8px',
    paddingRight: '8px',
    display: 'flex',
    overflow: 'visible',
    position: 'relative',
    flexDirection: 'column',
    alignItems: 'center',
    cursor: 'grab',
    userSelect: 'none',
    transition: 'all 0.2s ease',
    boxSizing: 'border-box',
    '&:lastChild': {
      borderRightStyle: 'none',
      borderRightWidth: 0,
    },
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.4)',
      cursor: 'grab',
    },
    '&:active': {
      cursor: 'grabbing',
      backgroundColor: 'rgba(0, 123, 255, 0.5)',
    },
    '&[draggable=true]': {
      cursor: 'grab',
      '&:hover': {
        backgroundColor: 'rgba(0, 123, 255, 0.4)',
        cursor: 'grab',
      },
      '&:active': {
        cursor: 'grabbing',
        backgroundColor: 'rgba(0, 123, 255, 0.5)',
      },
    },
  },
  tableHeaderCell: {
    ...textStyles.primary,
    fontWeight: '600',
    fontSize: calcFontSize(14),
    textAlign: 'center',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    width: '100%',
    style: {
      pointerEvents: 'none',
      userSelect: 'none'
    }
  },
  tableBody: {
    width: '100%',
    minWidth: 'fit-content',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#1A1F2580',
    borderBottomLeftRadius: '15px',
    borderBottomRightRadius: '15px',
    overflow: 'hidden',
    position: 'relative',
    zIndex: 1,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(255,255,255,0.2)',
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(255,255,255,0.2)',
    borderRightWidth: 2,
    borderRightColor: 'rgba(255,255,255,0.2)',
    boxShadow: `inset 0 ${calcSize(4)} ${calcSize(12)} rgba(0,0,0,0.15)`,
  },
  tableRow: {
    display: 'flex',
    flexDirection: 'row',
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    width: '100%',
    minWidth: 'fit-content',
    transition: 'all 0.2s ease',
    boxSizing: 'border-box',
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.1)',
      boxShadow: `0 ${calcSize(3)} ${calcSize(12)} rgba(0,123,255,0.15), inset 0 0 ${calcSize(20)} rgba(0,123,255,0.06)`,
      transform: 'translateX(3px)',
      opacity: 1,
    },
    '&:lastChild': {
      borderBottomWidth: '0',
      borderBottomLeftRadius: '15px',
      borderBottomRightRadius: '15px',
    },
  },
  tableRowEven: {
    backgroundColor: 'rgba(200, 210, 220, 0.08)',
    opacity: 0.8,
  },
  tableRowOdd: {
    backgroundColor: 'rgba(200, 210, 220, 0.15)',
    opacity: 0.8,
  },
  tableCell: {
    flexShrink: 0,
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '8px',
    paddingRight: '8px',
    borderRightStyle: 'solid',
    borderRightWidth: '1px',
    borderRightColor: 'rgba(255, 255, 255, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    boxSizing: 'border-box',
    '&:lastChild': {
      borderRightStyle: 'none',
      borderRightWidth: '0',
    },
  },
  tableCellText: {
    ...textStyles.primary,
    fontSize: calcFontSize(14),
    textAlign: 'center',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    width: '100%',
    cursor: 'pointer',
  },
  noDataText: {
    ...textStyles.primary,
    textAlign: 'center',
    margin: 20,
    fontSize: calcFontSize(16),
    opacity: 0.7,
  },
  errorBorder: {
    borderColor: 'red',
    borderWidth: 1,
  },
  errorText: {
    fontFamily: GLOBAL_FONT_FAMILY,
    color: '#ff4d4f',
    fontSize: calcFontSize(13),
    marginTop: 2,
    marginBottom: 'clamp(8px, 1.5vw, 12px)',
    letterSpacing: 0.5,
    textShadow: '0 1px 2px rgba(255,77,79,0.2)',
  },
  formSubmitButton: {
    backgroundColor: '#28a745',
    padding: 'clamp(8px, 1.6vw, 16px)',
    borderRadius: 'clamp(8px, 1.8vw, 18px)',
    alignSelf: 'center',
    marginTop: 'clamp(10px, 2vw, 20px)',
    marginBottom: 'clamp(20px, 4vw, 60px)',
    marginLeft: 'clamp(6px, 1vw, 10px)',
    marginRight: 'clamp(6px, 1vw, 10px)',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    boxShadow: `0 clamp(6px, 1.2vw, 12px) clamp(14px, 2.8vw, 28px) rgba(40,167,69,0.35), 
                0 clamp(3px, 0.6vw, 6px) clamp(7px, 1.4vw, 14px) rgba(0,0,0,0.25), 
                inset 0 clamp(-1.5px, -0.3vw, -3px) clamp(5px, 1vw, 10px) rgba(21,87,36,0.5), 
                inset 0 clamp(1.5px, 0.3vw, 3px) clamp(5px, 1vw, 10px) rgba(52,206,87,0.35),
                inset clamp(-1px, -0.2vw, -2px) 0 clamp(3px, 0.6vw, 6px) rgba(21,87,36,0.3),
                inset clamp(1px, 0.2vw, 2px) 0 clamp(3px, 0.6vw, 6px) rgba(52,206,87,0.3)`,
    borderWidth: 1,
    borderColor: 'rgba(52,206,87,0.3)',
    minWidth: 'clamp(100px, 20vw, 200px)',
    paddingHorizontal: 'clamp(10px, 2vw, 24px)',
    maxWidth: '90%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    '&:hover': {
      transform: 'translateY(-4px) scale(1.05)',
      boxShadow: `0 clamp(8px, 1.5vw, 15px) clamp(18px, 3.5vw, 35px) rgba(40,167,69,0.6), 0 clamp(2px, 0.5vw, 5px) clamp(8px, 1.5vw, 15px) rgba(0,0,0,0.3), 0 0 clamp(15px, 3vw, 30px) rgba(40,167,69,0.4)`,
      backgroundColor: '#1e7e34',
    },
    '&:active': {
      transform: 'translateY(-2px) scale(0.98)',
      boxShadow: `0 clamp(2px, 0.5vw, 5px) clamp(8px, 1.5vw, 15px) rgba(0,0,0,0.3), inset 0 clamp(1.5px, 0.3vw, 3px) clamp(4px, 0.8vw, 8px) rgba(0,0,0,0.3)`,
    },
  },
  formSubmitButtonText: {
    ...textStyles.primary,
    fontSize: 'clamp(12px, 1.6vw, 16px)',
    fontWeight: '600',
    lineHeight: 'clamp(16px, 2vw, 20px)',
    textAlign: 'center',
    width: '100%',
  },
  filterContainer: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: 4,
    width: '100%',
    zIndex: 3,
    boxSizing: 'border-box',
    overflow: 'visible',
  },
  filterInput: {
    backgroundColor: 'rgba(30, 35, 45, 0.9)',
    borderRadius: 999,
    padding: 4,
    fontSize: calcFontSize(12),
    width: '100%',
    height: 32,
    minHeight: 32,
    maxHeight: 32,
    border: '1px solid rgba(0, 123, 255, 0.3)',
    outlineWidth: 0,
    boxSizing: 'border-box',
    display: 'block',
    color: '#fff',
    fontFamily: GLOBAL_FONT_FAMILY,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    '&:hover': {
      borderColor: 'rgba(0, 123, 255, 0.6)',
      boxShadow: '0 0 8px rgba(0, 123, 255, 0.4), 0 0 16px rgba(0, 123, 255, 0.2), inset 0 1px 3px rgba(0, 0, 0, 0.1)',
      filter: 'brightness(1.1)',
    },
    '&:focus': {
      borderColor: 'rgba(0, 123, 255, 0.8)',
      backgroundColor: 'rgba(30, 35, 45, 1)',
      boxShadow: '0 0 12px rgba(0, 123, 255, 0.5), 0 0 24px rgba(0, 123, 255, 0.3), inset 0 1px 3px rgba(0, 0, 0, 0.1)',
      filter: 'brightness(1.15)',
    },
    '&::placeholder': {
      color: 'rgba(255, 255, 255, 0.5)',
    },
  },
  filterSelect: {
    width: '100%',
    height: 32,
    minHeight: 32,
    maxHeight: 32,
    padding: 4,
    fontSize: calcFontSize(12),
    backgroundColor: 'rgba(30, 35, 45, 0.9)',
    border: '1px solid rgba(0, 123, 255, 0.3)',
    borderRadius: 999,
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxSizing: 'border-box',
    fontFamily: GLOBAL_FONT_FAMILY,
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: 'rgba(30, 35, 45, 1)',
      borderColor: 'rgba(0, 123, 255, 0.5)',
    },
  },
  filterSelectText: {
    fontFamily: GLOBAL_FONT_FAMILY,
    fontSize: calcFontSize(12),
    color: '#fff',
    textAlign: 'center',
  },
  paginationContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(26, 31, 37, 0.8)',
    borderRadius: 12,
    marginVertical: 8,
    marginHorizontal: 8,
    backdropFilter: 'blur(8px)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderStyle: 'solid',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)',
  },
  rowsPerPageContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  rowsPerPageSelect: {
    display: 'flex',
    flexDirection: 'row',
    gap: calcSize(6),
    padding: calcSize(4),
  },
  rowsPerPageOption: {
    padding: calcSize(6),
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    height: calcSize(32),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: calcSize(40),
    border: '2px solid rgba(255, 255, 255, 0.12)',
    boxShadow: `0 ${calcSize(3)} ${calcSize(8)} rgba(0,0,0,0.2), inset 0 ${calcSize(1)} ${calcSize(2)} rgba(255,255,255,0.08)`,
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.2)',
      transform: 'translateY(-3px) scale(1.08)',
      boxShadow: `0 ${calcSize(6)} ${calcSize(16)} rgba(0, 123, 255, 0.25), 0 0 ${calcSize(12)} rgba(0, 123, 255, 0.12)`,
    },
    '&:active': {
      transform: 'translateY(-1px) scale(1.03)',
      boxShadow: `0 ${calcSize(2)} ${calcSize(6)} rgba(0,0,0,0.2), inset 0 ${calcSize(2)} ${calcSize(4)} rgba(0,0,0,0.2)`,
    },
  },
  rowsPerPageOptionActive: {
    backgroundColor: 'rgba(0, 123, 255, 0.3)',
    border: '2px solid rgba(0, 123, 255, 0.5)',
    boxShadow: `0 ${calcSize(6)} ${calcSize(16)} rgba(0, 123, 255, 0.3), 0 0 ${calcSize(20)} rgba(0, 123, 255, 0.15), inset 0 ${calcSize(1)} ${calcSize(2)} rgba(255,255,255,0.15)`,
    transform: 'translateY(-2px)',
  },
  rowsPerPageOptionText: {
    ...textStyles.primary,
    fontSize: calcFontSize(12),
    fontWeight: '500',
    textShadow: 'none',
  },
  rowsPerPageOptionTextActive: {
    fontWeight: '600',
    color: '#fff',
  },
  paginationControls: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: calcSize(8),
    marginLeft: calcSize(16),
  },
  paginationButton: {
    padding: calcSize(6),
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    height: calcSize(32),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: calcSize(32),
    border: '2px solid rgba(255, 255, 255, 0.15)',
    boxShadow: `0 ${calcSize(4)} ${calcSize(10)} rgba(0,0,0,0.2), inset 0 ${calcSize(1)} ${calcSize(2)} rgba(255,255,255,0.1)`,
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.25)',
      transform: 'translateY(-3px) scale(1.1)',
      boxShadow: `0 ${calcSize(8)} ${calcSize(20)} rgba(0, 123, 255, 0.3), 0 0 ${calcSize(15)} rgba(0, 123, 255, 0.15)`,
    },
    '&:active': {
      transform: 'translateY(-1px) scale(1.05)',
      boxShadow: `0 ${calcSize(3)} ${calcSize(8)} rgba(0,0,0,0.2), inset 0 ${calcSize(2)} ${calcSize(4)} rgba(0,0,0,0.2)`,
    },
  },
  paginationButtonDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      transform: 'none',
      boxShadow: 'none',
    },
  },
  paginationButtonText: {
    ...textStyles.primary,
    fontSize: calcFontSize(12),
    fontWeight: '600',
    textShadow: 'none',
  },
  paginationText: {
    ...textStyles.primary,
    fontSize: calcFontSize(12),
    fontWeight: '500',
    minWidth: 80,
    textAlign: 'center',
  },
  columnSelector: {
    position: 'relative',
    zIndex: 101,
  },
  columnSelectorButton: {
    backgroundColor: 'rgba(0, 123, 255, 0.3)',
    paddingVertical: calcSize(8),
    paddingHorizontal: calcSize(24),
    borderRadius: 999,
    height: calcSize(36),
    minWidth: calcSize(180),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    userSelect: 'none',
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.4)',
    },
  },
  columnSelectorButtonText: {
    fontFamily: GLOBAL_FONT_FAMILY,
    color: '#fff',
    fontSize: calcFontSize(14),
    fontWeight: '500',
    letterSpacing: '0.5px',
  },
  columnSelectorDropdown: {
    position: 'absolute',
    top: '100%',
    left: '0',
    backgroundColor: 'rgba(26, 31, 37, 0.98)',
    borderRadius: calcSize(16),
    paddingTop: calcSize(12),
    paddingBottom: calcSize(12),
    paddingLeft: calcSize(12),
    paddingRight: calcSize(12),
    maxHeight: calcSize(400),
    overflowY: 'auto',
    boxShadow: `0 ${calcSize(8)} ${calcSize(24)} rgba(0,0,0,0.4)`,
    minWidth: calcSize(250),
    backdropFilter: 'blur(10px)',
    borderStyle: 'solid',
    pointerEvents: 'auto',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    display: 'flex',
    flexDirection: 'column',
    gap: calcSize(4),
    zIndex: 102,
    marginTop: calcSize(8),
  },
  columnSelectorItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    cursor: 'grab',
    paddingVertical: calcSize(8),
    paddingHorizontal: calcSize(12),
    backgroundColor: 'transparent',
    borderRadius: calcSize(8),
    transition: 'all 0.2s ease',
    userSelect: 'none',
    pointerEvents: 'auto',
    '&:hover': {
      backgroundColor: 'rgba(255,255,255,0.1)',
    },
    '&:active': {
      cursor: 'grabbing',
      backgroundColor: 'rgba(0, 123, 255, 0.2)',
    },
  },
  checkbox: {
    width: calcSize(18),
    height: calcSize(18),
    borderStyle: 'solid',
    borderWidth: calcSize(2),
    borderColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: calcSize(4),
    marginRight: calcSize(12),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  },
  checkboxChecked: {
    backgroundColor: '#007bff',
    borderStyle: 'solid',
    borderWidth: 'clamp(1px, 0.2vw, 2px)',
    borderColor: '#007bff',
    color: '#fff',
  },
  columnSelectorItemText: {
    fontFamily: GLOBAL_FONT_FAMILY,
    color: '#fff',
    fontSize: 'clamp(10px, 1.4vw, 14px)',
    fontWeight: '500',
    lineHeight: 'clamp(14px, 1.8vw, 18px)',
  },
  tableControls: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: calcSize(8),
    paddingTop: calcSize(8),
    paddingBottom: calcSize(8),
    paddingLeft: 0,
    paddingRight: 0,
    borderRadius: calcSize(12),
    backgroundColor: 'transparent',
    position: 'relative',
    zIndex: 100,
    gap: calcSize(16),
    width: '100%',
    boxSizing: 'border-box',
    flexWrap: 'wrap',
    overflow: 'hidden',
  },
  tableControlsRight: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: calcSize(8),
    flex: 1,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    maxWidth: '100%',
    boxSizing: 'border-box',
  },
  dropdownContainer: {
    position: 'absolute',
    zIndex: 2001,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    padding: 8,
    borderRadius: 8,
    marginTop: 4,
    maxHeight: 300,
    top: '100%',
    left: 0,
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    overflowY: 'auto',
  },
  dropdownParent: {
    position: 'relative',
    zIndex: 2000,
  },
  filterDropdownContainer: {
    position: 'absolute',
    top: '100%',
    left: 0,
    backgroundColor: 'rgba(20, 25, 30, 0.98)',
    borderRadius: calcSize(12),
    paddingVertical: calcSize(6),
    paddingHorizontal: calcSize(6),
    minWidth: calcSize(150),
    boxShadow: `0 ${calcSize(8)} ${calcSize(24)} rgba(0,0,0,0.5), 0 ${calcSize(4)} ${calcSize(12)} rgba(0,123,255,0.3), 0 0 ${calcSize(20)} rgba(0,123,255,0.2)`,
    borderWidth: 1,
    borderColor: 'rgba(0, 123, 255, 0.5)',
    borderStyle: 'solid',
    zIndex: 9999,
    marginTop: calcSize(4),
    backdropFilter: 'blur(12px)',
    pointerEvents: 'auto',
  },
  filterDropdownItem: {
    paddingVertical: calcSize(6),
    paddingHorizontal: calcSize(10),
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    pointerEvents: 'auto',
    borderRadius: calcSize(8),
    marginBottom: calcSize(2),
    border: '1px solid transparent',
    fontFamily: GLOBAL_FONT_FAMILY,
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.15)',
      transform: 'translateX(4px)',
      border: '1px solid rgba(0, 123, 255, 0.3)',
      boxShadow: `0 ${calcSize(2)} ${calcSize(8)} rgba(0,123,255,0.2)`,
    },
  },
  filterDropdownItemText: {
    fontFamily: GLOBAL_FONT_FAMILY,
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: calcFontSize(12),
    fontWeight: '400',
    pointerEvents: 'none',
  },
  filterDropdownItemActive: {
    backgroundColor: 'rgba(0, 123, 255, 0.25)',
    borderLeftWidth: 3,
    borderLeftColor: 'rgba(0,123,255,1)',
    paddingLeft: calcSize(10),
    borderWidth: 1,
    borderColor: 'rgba(0, 123, 255, 0.6)',
    boxShadow: `0 0 ${calcSize(12)} rgba(0,123,255,0.4), inset 0 0 ${calcSize(8)} rgba(0,123,255,0.1)`,
    fontWeight: '700',
  },
  filterOperatorContainer: {
    position: 'relative',
    width: '100%',
    zIndex: 4,
    boxSizing: 'border-box',
    overflow: 'visible',
  },
  filterOperatorButton: {
    backgroundColor: 'rgba(30, 35, 45, 0.9)',
    padding: 4,
    borderRadius: 999,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: 32,
    minHeight: 32,
    maxHeight: 32,
    boxSizing: 'border-box',
    border: '1px solid rgba(0, 123, 255, 0.3)',
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: 'rgba(30, 35, 45, 1)',
      borderColor: 'rgba(0, 123, 255, 0.5)',
      boxShadow: '0 0 8px rgba(0, 123, 255, 0.2)',
    },
  },
  filterOperatorText: {
    fontFamily: GLOBAL_FONT_FAMILY,
    color: '#fff',
    fontSize: calcFontSize(12),
  },
  '@viewport': {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
  },
  '@-ms-viewport': {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
  },
  touchAction: {
    style: {
      pointerEvents: 'none'
    }
  },
  dragIndicator: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '4px',
    backgroundColor: '#007bff',
    opacity: 0,
    transition: 'opacity 0.2s ease',
  },
  dragIndicatorVisible: {
    opacity: 1,
  },
});

export default styles;
export { GLOBAL_FONT_FAMILY };
